config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [:index, :show, :new, :create] do
    resources :followings, only: [ :create ]
    resources :reviews, only: [ :index, :new, :create ]
    resources :posts, only: [:new, :create] do
      collection do
        get :discussion
        get :devlogs
      end
    end
  end

  resources :followings, only: [ :index, :destroy ]

  resources :posts, only: [:destroy] do
    resources :replies, only: [:create]
  end

  resources :posts, only: [] do
    member do
      put "like" => "posts#like"
      get "update_counter" => "posts#update_counter"
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :users

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="box banner-image">
    <%= cl_image_tag(@game.photos.last.key) %>
  </div>
  <div class="box banner-content">
    <%= cl_image_tag(@game.photos.first.key, class: "avatar") %>
    <p class="developer">Developed by <%= @game.user.nickname %></p>
    <div class="game-box">
      <% if @game.user != current_user %>
        <div>
        <p class="box-title">Reviews</p>
        <% if @game.reviews.empty? %>
          <p class="box-info"><i>No reviews available</i></p>
        <% else %>
          <% @review_tally = 0.00 %>
          <% @game.reviews.each do |review| %>
            <% @review_tally += review.rating %>
          <% end %>
          <p class="box-info"><%= (@review_tally = (@review_tally / @game.reviews.count)).round(2)%>/5</p>
        <% end %>
        </div>
        <div>
          <p class="box-title">Published</p>
          <p class="box-info"><%= @game.created_at.strftime("%d/%m/%Y") %></p>
        </div>
        <div>
          <p class="box-title">Version</p>
          <p class="box-info">1.0.1</p>
        </div>
      <% else %>
        <div>
          <p class="box-title">Purchases</p>
          <p class="box-info"><%= @game.orders.length %></p>
        </div>
        <div>
          <p class="box-title">Views</p>
          <p class="box-info"><%= @game.visit_counter %></p>
        </div>
        <div>
          <p class="box-title">Threads</p>
          <p class="box-info"><%= @game.posts.where(category: "discussion").length %></p>
        </div>
        <div>
        <p class="box-title">Reviews</p>
        <% if @game.reviews.empty? %>
          <p class="box-info">0</p>
        <% else %>
          <% @review_tally = 0.00 %>
          <% @game.reviews.each do |review| %>
            <% @review_tally += review.rating %>
          <% end %>
          <p class="box-info"><%= (@review_tally = (@review_tally / @game.reviews.count)).round(2)%>/5 (<%= @game.reviews.length %>)</p>
        <% end %>
        </div>
      <% end %>
    </div>
    <div class="banner-top">
      <h1 class="banner-title"><%= @game.title %></h1>
      <div class="system-icons">
        <% @game.platforms.each do |platform| %>
          <% if platform.name == "Windows" %>
            <i class="fab fa-windows platform-icon" ></i>
          <% elsif platform.name == "MacOS" %>
            <i class="fab fa-apple platform-icon"></i>
          <% elsif platform.name == "Linux" %>
            <i class="fab fa-linux platform-icon"></i>
            <% elsif platform.name == "Web" %>
            <i class="fas fa-globe-europe platform-icon"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <p class="banner-category">#<%= @game.category %></p>
    <p class="banner-description"><%= @game.description %></p>
    <% if @game.user != current_user %>
      <div class="banner-order">
        <%= form_tag orders_path do %>
          <%= hidden_field_tag 'game_id', @game.id %>
          <%= submit_tag 'Buy Now', class: 'banner-buy-button' %>
        <% end %>
        <h3><%= humanized_money_with_symbol(@game.price)%></h3>
      </div>
    <% end %>
  </div>
</div>
<div class="row d-flex justify-content-center form-banner">
  <div class="col-8">
    <div class="banner-links">
      <%= link_to "Home", game_path(@game), class:"middle" %>
      <%= link_to "Discussion", discussion_game_posts_path(@game), class:"middle" %>
      <%= link_to "Devlogs", devlogs_game_posts_path(@game), class:"middle" %>
      <%= link_to "Reviews", game_reviews_path(@game), class:"middle" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="wrapper">
  <div id ="footer" class="footer align-items-center">
    <div>
      <div>
        <ul class="d-flex justify-space-between p-0 align-items-center m-0">
          <li class="footer-item mr-3 social-media-link"><a href="#"><i class="fab fa-facebook"></i></a></li>
          <li class="footer-item mr-3"><a href="#" id="footer-item">ABOUT</a></li>
          <li class="footer-item mr-3"><a href="#" id="footer-item">FAQ</a></li>
          <li class="footer-item mr-3"><a href="#" id="footer-item">BLOG</a></li>
          <li class="footer-item"><a href="#"class="footer-item">CONTACT US</a></li>
        </ul>
      </div>
      <div class="d-flex justify-content-center">
        <p>Copyright © 2020 LevelUp</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="nav-container">
    <div class="nav-logo">
      <span></span>
      <%= link_to root_path do %>
        <%= image_tag "logo.svg", class: "logo-link" %>
        <% end %>
    </div>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
      <ul class="page-icons navbar-nav mr-auto" id="page-icons">
        <% @url = request.path_info %>
        <%= link_to games_path do %>
          <li class="page-icon middle nav-item mx-3">
            <i class="fas fa-gamepad"></i>
          </li>
        <% end %>
        <%= link_to followings_path, class: "#{'active' if @url.include?('followings')}" do %>
          <li class="page-icon middle nav-item mx-3">
            <i class="far fa-eye"></i>
          </li>
        <% end %>
        <%= link_to games_path do %>
          <li class="page-icon middle nav-item mx-3">
            <i class="fas fa-file-alt"></i>
          </li>
        <% end %>
        <%= link_to games_path do %>
          <li class="page-icon middle nav-item mx-3">
            <i class="fas fa-file-code"></i>
          </li>
        <% end %>
      </ul>
  </div>
  <div class="nav-container">
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav mr-0 d-flex align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item dropdown d-flex align-items-center mr-auto">
            <%= cl_image_tag(current_user.photo.key, class: "avatar")%>
            <div class="nav-username">
              <%= current_user.nickname %>
            </div>
          </li>
            <li class="settings-icon middle nav-item dropdown mr-2 d-flex align-items-center justify-content-center">
              <i class="fas fa-sliders-h" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false""></i>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Add a game", new_game_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
        <% else %>
          <li class="nav-item mr-3">
            <%= link_to "Login", new_user_session_path, class: "nav-link", id: "login-button" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>