config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [:index, :show, :new, :create] do
    resources :followings, only: [ :create ]
    resources :reviews, only: [ :index, :new, :create ]
    resources :posts, only: [:new, :create] do
      collection do
        get :discussion
        get :devlogs
      end
    end
  end

  resources :followings, only: [ :index, :destroy ]

  resources :posts, only: [:destroy] do
    resources :replies, only: [:create]
  end

  resources :posts, only: [] do
    member do
      put "like" => "posts#like"
      get "update_counter" => "posts#update_counter"
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :users

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :games_platforms, dependent: :destroy
  has_many :platforms, through: :games_platforms
  has_many_attached :photos
  monetize :price_cents
  has_many :followings, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :price, presence: true


  include PgSearch::Model
  pg_search_scope :search_by_title_and_description_and_category,
   against: [:title, :description, :category],
   using: {
    tsearch: {prefix: true}
   }

  def increase_visit
   self.visit_counter += 1
   save!
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:hide_welcome]
      session[:hide_welcome] = true
    end
    if params[:search].present?
      search = params[:search]
      if search[:platform].last.present? && search[:price].present?
        @games = Game.where("price_cents < ?", search[:price].to_i).select do |game|
          game.platform_ids.select do |id|
            search[:platform].include?("#{id}")
          end.present?
        end
        # @games = Game.where(platform: search[:platform]).where("price_cents < ?", search[:price].to_i)
      elsif search[:platform].last.empty?
        @games = Game.where("price_cents < ?", search[:price].to_i)
      elsif search[:platform].last.present?
        # @games = Game.joins(:games_platforms).where(platform_id: search[:platform])
        @games = Game.all.select do |game|
          game.platform_ids.select do |id|
            search[:platform].include?("#{id}")
          end.present?
        end
        # @games = Game.where(platform: search[:platform])
      else
        @games = Game.all
      end
    elsif params[:query].present?
      @games = Game.search_by_title_and_description_and_category(params[:query])
    else
      @games = Game.all
    end

    # .paginate(page: params[:page], per_page: 12)

      # elsif search[:platform].length > 2 && !search[:price].last.empty?
      #   @games = (Game.where(platform: search[:platform][1]).and(Game.where(platform: search[:platform][2]))).where("price_cents < ?", search[:price].last.to_i)

    # elsif params[:platform].present?
    #   @games = @games.where(platform: params[:platform])
    # elsif params[:price_cents].present?
    #   if params[:price_cents] == "£10 or less"
    #     @games = @games.where("price_cents < ?",1000)
    #   end
    # end
  end

  def show
    @game = Game.find(params[:id])
    @posts = @game.posts.where(category: 'post')
    @post = Post.new
    @game.increase_visit
  end

  def new
    @game = Game.new
  end

  def create

    @game = Game.new(games_params)
    @game.user = current_user
    if @game.save
      redirect_to game_path(@game), notice: "Game was succesfully created."
    else
      render :new
    end
  end

  private

  def games_params
    params.require(:game).permit(:title, :description, :category, :price, platform_ids: [], photos: [])
  end
end

app/views/games/_session-display.html.erb
    <div class="welcome-form-style" id="welcome-modal">
      <div class="d-flex align-items-center flex-column p-5">
        <h2>Hi there!</h2>
        <h6>We are happy to have you browsing our handpicked games!</h6>
        <p>Here's what you can do:</p>
        <p><i class="fas fa-scroll"></i>  Browse Games</p>
        <p><i class="fas fa-heart"></i>  Follow Games</p>
        <p><i class="fas fa-headset"></i>  Communicate with developers and give feedback!!</p>
        <p><i class="fas fa-gamepad"></i>  Download awesome games!</p>
        <%= link_to "Got it!", games_path(hide_welcome: true), class:"welcome-button"%>
      </div>
      <div class="lower"></div>
    </div>

app/views/games/index.html.erb
<% unless session[:hide_welcome] %>
  <%= render "session-display" %>
<% end %>

<div id="body-tag">
<div class="hero">
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="false">
  <div class="carousel-inner h-100 w-75 image-margin">
    <% @games.each_with_index do |game, index| %>
    <div class="carousel-item <%= 'active' if index.zero? %> h-100">
      <%= link_to game_path(game), class:"text-decoration-none w-75" do %>
        <div class="d-flex h-100">
        <%= cl_image_tag(game.photos.last.key, crop: :fit, class:"d-block h-100  ml-0 game-image") %>
        <div class="image-sidebox">
          <h4><%= game.title %></h4>
          <p class="game-tag"> <%= "##{game.category}"  %> </p>
          <p><%= game.description %></p>


            <% @current_following = current_user.followings.find { |item| item[:game_id] == game.id} if user_signed_in?%>

            <% if @current_following %>
              <div class="following-button" id="following-button">
                <%= link_to "✓ Following", following_path(@current_following.id), method: :delete %>
              </div>
            <% else %>
            <div class="follow-button" id="follow-button">
                <%= link_to "+ Follow game!", game_followings_path(game), method: :post %>
            </div>
            <% end %>
        </div>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <a class="carousel-control-prev carousel-button" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

<div class="row mx-0">
  <div class="col-0 col-md-2 filters-background">
    <div class="container-fluid filters-content">
      <h3 class="mb-0">Filter Games</h3>
      <div class="filters-type">
        <%= simple_form_for :search, url: games_path, method: :get do |f| %>
        <%= f.input :platform, collection: Platform.all, as: :check_boxes, input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item' %>
        <%= f.input :price, collection:[["Free", 1], ["£10 or less", 1000], ["£20 or less", 2000]], as: :radio_buttons %>
        <%= f.submit "Filter", class:"filter-button"%>
        <% end  %>
        </div>
    </div>
  </div>
    <div class="col-12 col-md-10 games-container">
      <div class="games-background">
        <div class="container-fluid">
          <div class="d-flex justify-content-between mt-1 games-search align-items-center">
            <h2 class="mb-0">Latest Featured Games</h2>
              <%= form_tag games_path, method: :get do %>
              <div class="form-container-index d-flex">
              <%= text_field_tag :query,
                params[:query],
                class: "form-control search-form-index",
                placeholder: "Find a game!"
              %>
              <%= submit_tag "Search", class: "btn btn-primary btn-search-index" %>
               </div>
            <% end %>
          </div>
          <div class="games-box">
            <% @games.each do |game| %>
            <%= link_to game_path(game), class:"text-decoration-none" do %>
                <div class="games-card">
                  <div class="game-card-info">
                    <%= cl_image_tag(game.photos.first.key, class: "game-image") %>
                    <div class="game-card-text">
                      <p class="mb-0 game-title"><%= game.title %></p>
                      <p class="game-tag"><%="##{game.category}"%></p>
                      <p class="game-description text-break"><%= game.description.truncate(150) %></p>
                        <%= form_tag orders_path do %>
                        <%= hidden_field_tag 'game_id', game.id %>
                        <%= submit_tag humanized_money_with_symbol(game.price), class:"game-card-button"%>
                        <% end %>
                    </div>
                  </div>
                </div>
            <% end %>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>
</div>

<!-- will_paginate @games
 -->

<!-- submit_tag humanized_money_with_symbol(game.price), class:"game-card-button" -->

app/views/games/new.html.erb
<div class="container mt-3">
  <div class="row d-flex justify-content-center form-container">
    <div class="col-8 new-form">
      <h1 class="text-center">Add a game</h1>
        <%= simple_form_for(@game) do |f| %>
          <%= f.input :title, placeholder: "Title" %>
          <%= f.input :description, placeholder: "Description" %>
          <%= f.input :category, placeholder: "Category" %>
          <%= f.association :platforms, placeholder: "Platforms", collection: Platform.all, as: :check_boxes %>
          <%= f.input :price %>
          <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'd-none' }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
          <%= f.button :submit, "Add your game!", class: "btn btn-success submit-button" %>
        <% end %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<%= render 'shared/banner' %>


<div class="box">
  <div class="box">
    <div class="gallery-container">
      <div class="gallery js-flickity" data-flickity-options='{ "wrapAround": true }'>
        <% @game.photos.each do | photo | %>
          <div class="gallery-cell">
            <%= cl_image_tag(photo.key, crop: :fill) %>
          </div>
        <% end %>
        <% if @game.photos.length < 5 %>
            <% @count = 5 - @game.photos.length %>
            <% @count.times do  %>
              <% @game.photos.each do | photo | %>
                <div class="gallery-cell">
                  <%= cl_image_tag(photo.key, crop: :fill) %>
                </div>
              <% end %>
            <% end %>
        <% end %>
      </div>
    </div>




  <div class="row">
    <div class="col-lg-12 col-xl-5">
      <div class="row-left">
        <div class="card-show-left">
        <h5>Latest Discussions</h5>
          <% if @game.posts.where(category: 'discussion').empty? %>
            <p>No discussion available</p>
          <% else %>

          <div class="discussion-top">
            <%= cl_image_tag(@game.posts.where(category: 'discussion').last.user.photo.key, class: "avatar") %>
            <div class="user-date">
              <h2><%= @game.posts.where(category: 'discussion').last.user.nickname %></h2>
              <p class="time"><%= time_ago_in_words(@game.posts.where(category: 'discussion').last.created_at) %></p>
            </div>
            <% if @game.user.id == @game.posts.where(category: 'discussion').last.user.id %>
              <div class="btn btn-success submit-button top-button">Developer</div>
            <% end %>
          </div>
          <div class="content-show-page">
            <%# if @game.posts.where(category: 'discussion').last.photo.attached? %>
              <%#= cl_image_tag(@game.posts.where(category: 'discussion').last.photo.key, class: "image-post") %>
            <%# end %>
            <p><%= @game.posts.where(category: 'discussion').last.content.truncate(240) %></p>
            <%= link_to "See more", discussion_game_posts_path(@game), class:"red" %>
          </div>
          <% end %>
      </div>

      <div class="card-show-left">
        <h5>Latest Devlogs</h5>
        <% if @game.posts.where(category: 'devlog').empty? %>
            <p>No devlogs available</p>
        <% else %>
        <div>
          <div class="discussion-top">
            <%= cl_image_tag(@game.posts.where(category: 'devlog').last.user.photo.key, class: "avatar") %>
            <div class="user-date">
              <h2><%= @game.posts.where(category: 'devlog').last.user.nickname %></h2>
              <p class="time"><%= time_ago_in_words(@game.posts.where(category: 'devlog').last.created_at) %></p>
            </div>
            <div class="btn btn-success submit-button top-button">Developer</div>
          </div>
          <div class="devlog-title-show-page">
            <p class="red">DEVLOG #<%= @game.posts.where(category: 'devlog').index(@game.posts.where(category: 'devlog').last) + 1 %></p>
            <h5 class="title"><%= @game.posts.where(category: 'devlog').last.title %></h5>
          </div>

          <div>
            <% if @game.posts.where(category: 'devlog').last.photo.attached? %>
              <%= cl_image_tag(@game.posts.where(category: 'devlog').last.photo.key, class: "image-post") %>
            <% end %>
            <p id="devlog-content"><%= @game.posts.where(category: 'devlog').last.content.truncate(240) %></p>
          </div>
          <%= link_to "See more", devlogs_game_posts_path(@game), class:"red" %>
        </div>
        <% end %>
      </div>

      <div class="card-show-left">
        <h5>Latest Reviews</h5>
        <% if @game.reviews.empty? %>
          <p>No reviews available</p>
        <% else %>
          <div class="discussion-top">
            <%= cl_image_tag(@game.reviews.last.user.photo.key, class: "avatar") %>
            <div class="user-date">
              <h2><%= @game.reviews.last.user.nickname %></h2>
              <p class="time"><%= time_ago_in_words(@game.reviews.last.created_at) %></p>
            </div>
            <div class="review-rating">
              <% @game.reviews.last.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
            </div>
          </div>
          <div>
            <p id="review-content-show-page"><%= @game.reviews.last.content.truncate(240) %></p>
          </div>
          <%= link_to "See more", game_reviews_path(@game), class:"red" %>
          <% end %>
      </div>
      </div>

    </div>


    <div class="col-lg-12 col-xl-7">
<!-- Form visible only to the game owner to make a post -->
      <% if @game.user == current_user%>
        <div class=" card-show-right">
            <div class="fake-form-container" id="anchor-for-posts">
              <%= cl_image_tag(@game.user.photo.key, class: "avatar") %>
              <div class="fake-form" data-toggle="modal" data-target="#myModal">What's new?</div>
            </div>
        </div>
      <% end %>

       <% if @game.posts.empty? %>
         <p id="no-posts">No posts available yet</p>
       <% end %>
<!-- Posts one under the other -->
       <% @posts.reverse.each do |post| %>
        <div class="card-show-right">
          <div class="card-show-header">
            <div class="inner-show-header">
            <%= cl_image_tag(@game.user.photo.key, class: "avatar") %>
              <span class="user-date">
                <h2><%= post.user.nickname %></h2>
                <p class="time"><%= time_ago_in_words(post.created_at) %></p>
              </span>
            </div>
<!-- Dropdown available only to the post author === game owner-->

            <% if @game.user == current_user%>
              <div class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-h"></i>
              </div>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Edit post", post_path(post), class:"dropdown-item #{'active' if controller_name == 'bookings' && action_name == 'index'}" %>
                <%= link_to "Delete post", post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class:"dropdown-item" %>
            </div>
          <% end %>
          </div>

          <div class="card-show-content">
            <p><%= post.title %></p>
            <p><%= post.content %></p>
          </div>
          <% if post.photo.attached? %>
            <%= cl_image_tag(post.photo.key, class: "image-post") %>
          <% end %>

<!-- number of commnets -->
          <div class="post-icons">
            <div class="post-like" data-controller="counter">
              <% if user_signed_in? %>
                <% if current_user.liked? post %>
                  <i class="fas fa-thumbs-up liked"></i>
                <% else %>
                  <%= link_to like_post_path(post), class:"thumbs-up", :"data-action" => "click->counter#refresh_post", :"data-id" => "#{post.id}", method: :put, remote: :true do %>
                    <i class="fas fa-thumbs-up"></i>
                  <% end %>
                <% end %>
              <% end %>
              <div class="counter">
                <span id="post-<%= post.id %>" data-target="counter.count"><%= post.get_likes.size %></span>
                <% if post.get_likes.size == 1 %>
                  <p class="text-like">like</p>
                <% else %>
                  <p class="text-like">likes</p>
                <% end %>
              </div>
            </div>

            <% if post.replies.count == 1 %>
              <p id="comment-number" data-post-count="<%= post.replies.count %>"><%= post.replies.count %> comment</p>
            <% else %>
              <p id="comment-number"><%= post.replies.count %> comments</p>
            <% end %>
  <!-- likes -->

          </div>
<!-- One reply-->
          <% if post.replies.count == 1 %>
            <div class="replies-container">
                <div class="reply-container" id="reply-<%= post.replies[-1].id %>">
                  <div class="reply-wrapper">
                    <%= cl_image_tag(post.replies[-1].user.photo.key, class: "avatar") %>
                    <p><%= post.replies[-1].content.html_safe %></p>
                  </div>
                  <p class="time"><%= time_ago_in_words(post.replies[-1].created_at) %></p>
                </div>
            </div>
          <% end %>
<!-- All the replies -->
          <% if post.replies.count > 0 %>
            <div class="replies-container hide">
              <% post.replies[0..-3].each do |reply| %>
                <div class="reply-container" id="reply-<%= reply.id %>">
                  <div class="reply-wrapper">
                    <%= cl_image_tag(reply.user.photo.key, class: "avatar") %>
                    <p><%= reply.content %></p>
                  </div>
                  <p class="time"><%= time_ago_in_words(reply.created_at) %></p>
                </div>
              <% end %>
            </div>
          <% end %>

<!-- Just last two replies -->
          <% if post.replies.count > 1 %>
          <div class="see-comments">View previous comments (<%= post.replies.count - 2 %>)</div>
          <div class="replies-container">
            <% post.replies[-2..-1].each do |reply| %>
              <div class="reply-container" id="reply-<%= reply.id %>">
                  <div class="reply-wrapper">
                    <%= cl_image_tag(reply.user.photo.key, class: "avatar") %>
                    <p><%= reply.content.html_safe %></p>
                  </div>
                  <p class="time"><%= time_ago_in_words(reply.created_at) %></p>
              </div>
            <% end %>
          </div>
          <div class="see-less hide">See less</div>
          <% end %>


<!-- Form for 1st tier reply-->
          <div class="card-show-reply">
            <%= simple_form_for([post, Reply.new], remote: true, html: {class: 'form-inline'}, authenticity_token: true) do |f| %>
              <% if user_signed_in? %>
                <%= cl_image_tag(current_user.photo.key, class: "avatar-small") %>
                <%= f.input :content, placeholder: "Comment on that...", label: false %>
              <% end %>

            <% end  %>
          </div>


        </div>
      <% end %>

    </div>

  </div>
  </div>


</div>


<div class="box">
  <div class="row">
    <div class="col-md-12">
      <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-md">
          <div class="modal-content">
            <div class="modal-header">
              <h5>Create a post</h5>
              <button id="close-button-container" type="button" class="close" data-dismiss="modal" aria-label="Close">
                <small aria-hidden="true" id="close-button" class="mdi mdi-close-circle-outline text-white"></small>
              </button>
            </div>
            <div class="modal-body">
              <div class="post-form-body-top">
                <%= cl_image_tag(@game.user.photo.key, class: "avatar") %>
                <span>@<%= @game.user.nickname %></span>
              </div>
              <div class="post-form">
                <%= simple_form_for [@game, @post] do |f| %>
                  <%= f.input :content, placeholder: "What's new?", label: false %>
                  <%= f.input :category, as: :hidden, input_html: { value: params[:category] || "post" } %>
                  <div class="post-form-photo">
                    <%= f.input :photo, as: :file, input_html: { class: 'd-none' }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
                  </div>
                  <div class="line-form"></div>
                  <div class="modal-footer">
                    <%= f.button :submit, "Post", class: "btn btn-success btn-for-post" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>